spring:
  application:
   name: discovery-server

server:
  port: 9057

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false #para buscar infoprmacionde otro servidor tambiner se ddebe de
                          #establecer la direccion A BUSCAR
    server-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

