server:
  port: 0


spring:
  application:
    name: msvc-inventory
    #config:
    # import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inventorybd
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  #config eureka
#eureka client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9057/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
