server:
  port: 0

spring: #config mysql
  application:
    name: msvc-orders
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ordersbd
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect


#eureka client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9057/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
