server:
  port: 0

spring:
  application:
    name: kafka_notificacion
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9057/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: health
    base_path:
      -/actuator/notifications
